openapi: 3.0.4
info:
  title: myproject
  description: desc
  version: 1.0.0
servers:
- url: http://localhost:8000
  description: dev
paths:
  /endpoint1:
    summary: endpoint1 summary
    description: endpoint1 description
    post:
      tags:
      - tag1
      summary: endpoint1 summary
      description: endpoint1 description
      externalDocs:
        description: example
        url: http://example.com
      operationId: endpoint1_operation
      parameters:
      - required: true
        deprecated: false
        style: simple
        schema:
          title: token
          type: string
        name: token
        in: header
        allowEmptyValue: false
        allowReserved: false
      - required: true
        deprecated: false
        style: simple
        schema:
          title: token2
          type: string
        name: token2
        in: header
        allowEmptyValue: false
        allowReserved: false
      - required: true
        deprecated: false
        style: simple
        schema:
          title: token3
          type: string
        name: token3
        in: header
        allowEmptyValue: false
        allowReserved: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint1.Endpoint1BodyModel'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint1.Resp'
      deprecated: false
  /endpoint2:
    get:
      tags:
      - tag1
      - tag2
      operationId: 270ca061c1a94d30a6dcd2731910b15a
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint2.Endpoint2BodyModel'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint2.Resp'
      deprecated: false
components:
  schemas:
    tests.test_openapi.test_openapi_base.endpoint1.Ctx:
      title: Ctx
      required:
      - page
      - size
      - search
      type: object
      properties:
        page:
          title: Page
          type: integer
        size:
          title: Size
          type: integer
        search:
          title: Search
          type: string
        fixed:
          $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint1.Fixed'
          default:
            foo: bar
            
      media_type: application/json
    tests.test_openapi.test_openapi_base.endpoint1.Fixed:
      title: Fixed
      required:
      - foo
      type: object
      properties:
        foo:
          title: Foo
          type: string
    tests.test_openapi.test_openapi_base.endpoint1.Resp:
      title: Resp
      required:
      - message
      type: object
      properties:
        message:
          title: Message
          type: string
        ctx:
          $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint1.Ctx'
          default:
            page: 1
            size: 10
            search: hello
            fixed:
              foo: bar
    tests.test_openapi.test_openapi_base.endpoint1.Endpoint1BodyModel:
      title: Endpoint1BodyModel
      required:
      - page
      - size
      - search
      type: object
      properties:
        page:
          title: page
          type: integer
        size:
          title: size
          type: integer
        search:
          title: search
          type: string
        fixed:
          title: fixed
          default:
            foo: bar
          $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint1.Fixed'
      media_type: application/json
    tests.test_openapi.test_openapi_base.endpoint2.Ctx:
      title: Ctx
      required:
      - page
      - size
      - search
      type: object
      properties:
        page:
          title: Page
          type: integer
        size:
          title: Size
          type: integer
        search:
          title: Search
          type: string
        fixed:
          $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint2.Fixed'
          default:
            foo: bar
      media_type: application/json
    tests.test_openapi.test_openapi_base.endpoint2.Fixed:
      title: Fixed
      required:
      - foo
      type: object
      properties:
        foo:
          title: Foo
          type: string
    tests.test_openapi.test_openapi_base.endpoint2.Resp:
      title: Resp
      required:
      - message
      type: object
      properties:
        message:
          title: Message
          type: string
        ctx:
          $ref: '#/components/schemas/tests.test_openapi.test_openapi_base.endpoint2.Ctx'
          default:
            page: 1
            size: 10
            search: hello
            fixed:
              foo: bar
    tests.test_openapi.test_openapi_base.endpoint2.Endpoint2BodyModel:
      title: Endpoint2BodyModel
      required:
      - name
      - age
      type: object
      properties:
        name:
          title: name
          type: string
        age:
          title: age
          type: integer
      media_type: application/json
tags:
- name: tag1
- name: tag2
