import typing as t

from unfazed.http import HttpRequest


class BaseAdmin(t.Protocol):
    name: str
    title: str
    serializer: t.Type

    async def has_view_perm(self, request: HttpRequest, *args, **kw) -> bool: ...
    async def has_change_perm(self, request: HttpRequest, *args, **kw) -> bool: ...
    async def has_delete_perm(self, request: HttpRequest, *args, **kw) -> bool: ...
    async def has_create_perm(self, request: HttpRequest, *args, **kw) -> bool: ...
    async def has_action_perm(self, request: HttpRequest, *args, **kw) -> bool: ...

    def get_actions(self) -> t.Dict[str, t.Any]: ...
